### ANS 1
70% percent have insurance plan 
40% are smoker who have insurance plan.
probabilty=0.57

### ANS 2
#### bernouli:
bernouli naive bayes theorem is used when feature of datasets are following bernoulli distribution or feature have only two outcome.
***
#### multinomial:
it is used when feature are in text it used nlp to convert text feature into 0,1_ _. 

### ANS 4
yes guassian naive bayes can be used for multi-class classification. the only conidition for naive bayes is that feature need to follow guassian distribution.


### ANS 3
naive bayes does not have bult-in mechanism to handle missing value.it assumes all features are binary(0 or 1). we should be carefull before using naive bayes as it affect the accuracy of the model.

### ANS 5

### Implementation

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns 
import warnings 
warnings.filterwarnings('ignore')

In [4]:
pip install ucimlrepo

  Obtaining dependency information for ucimlrepo from https://files.pythonhosted.org/packages/3e/4a/ecc3456479d687202b34ee42317c3a63e09793c9409a720052d38356431a/ucimlrepo-0.0.3-py3-none-any.whl.metadata
Note: you may need to restart the kernel to use updated packages.


In [5]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
spambase = fetch_ucirepo(id=94) 
  
# data (as pandas dataframes) 
X = spambase.data.features 
y = spambase.data.targets 
  
# metadata 
print(spambase.metadata) 
  
# variable information 
print(spambase.variables) 

{'uci_id': 94, 'name': 'Spambase', 'repository_url': 'https://archive.ics.uci.edu/dataset/94/spambase', 'data_url': 'https://archive.ics.uci.edu/static/public/94/data.csv', 'abstract': 'Classifying Email as Spam or Non-Spam', 'area': 'Computer Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 4601, 'num_features': 57, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': ['Class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1999, 'last_updated': 'Mon Aug 28 2023', 'dataset_doi': '10.24432/C53G6X', 'creators': ['Mark Hopkins', 'Erik Reeber', 'George Forman', 'Jaap Suermondt'], 'intro_paper': None, 'additional_info': {'summary': 'The "spam" concept is diverse: advertisements for products/web sites, make money fast schemes, chain letters, pornography...\n\nThe classification task for this dataset is to determine whether a given email is spam or not.\n\t\nOur collecti

In [12]:
df=pd.concat([X,y],axis=1)

In [13]:
df.head()

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0            0.00               0.64           0.64           0.0   
1            0.21               0.28           0.50           0.0   
2            0.06               0.00           0.71           0.0   
3            0.00               0.00           0.00           0.0   
4            0.00               0.00           0.00           0.0   

   word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0           0.32            0.00              0.00                0.00   
1           0.14            0.28              0.21                0.07   
2           1.23            0.19              0.19                0.12   
3           0.63            0.00              0.31                0.63   
4           0.63            0.00              0.31                0.63   

   word_freq_order  word_freq_mail  ...  char_freq_;  char_freq_(  \
0             0.00            0.00  ...         0.00        0.000   
1             0.00            0.94  ...         0.00        0.132   
2             0.64            0.25  ...         0.01        0.143   
3             0.31            0.63  ...         0.00        0.137   
4             0.31            0.63  ...         0.00        0.135   

   char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
0          0.0        0.778        0.000        0.000   
1          0.0        0.372        0.180        0.048   
2          0.0        0.276        0.184        0.010   
3          0.0        0.137        0.000        0.000   
4          0.0        0.135        0.000        0.000   

   capital_run_length_average  capital_run_length_longest  \
0                       3.756                          61   
1                       5.114                         101   
2                       9.821                         485   
3                       3.537                          40   
4                       3.537                          40   

   capital_run_length_total  Class  
0                       278      1  
1                      1028      1  
2                      2259      1  
3                       191      1  
4                       191      1  

[5 rows x 58 columns]

In [15]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [17]:
gb=GaussianNB()

In [18]:
gb.fit(X_train,y_train)

GaussianNB()

In [23]:
from sklearn.model_selection import cross_val_score

In [41]:
score=cross_val_score(gb,X,y,cv=10)

In [42]:
print(score)

[0.84381779 0.86304348 0.87826087 0.8673913  0.88478261 0.82826087
 0.8326087  0.8673913  0.63478261 0.7173913 ]


In [46]:
y_pred=gb.predict(X_test)

In [30]:
from sklearn.naive_bayes import BernoulliNB

In [31]:
bn=BernoulliNB()

In [32]:
bn.fit(X_train,y_train)

BernoulliNB()

In [38]:
score1=cross_val_score(bn,X,y,cv=10)

In [40]:
score1

array([0.88503254, 0.9173913 , 0.9       , 0.90869565, 0.89130435,
       0.92826087, 0.92608696, 0.89130435, 0.80869565, 0.7826087 ])

In [47]:
y_pred1=bn.predict(X_test)

In [35]:
from sklearn.naive_bayes import MultinomialNB

In [36]:
mb=MultinomialNB()

In [37]:
mb.fit(X_train,y_train)

MultinomialNB()

In [48]:
y_pred3=mb.predict(X_test)

In [43]:
score3=score=cross_val_score(mb,X,y,cv=10)

In [44]:
print(score3)

[0.79175705 0.79347826 0.80869565 0.83478261 0.82826087 0.77826087
 0.77826087 0.81304348 0.69347826 0.74347826]


In [45]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

### Results

In [49]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[649 237]
 [ 32 601]]
              precision    recall  f1-score   support

           0       0.95      0.73      0.83       886
           1       0.72      0.95      0.82       633

    accuracy                           0.82      1519
   macro avg       0.84      0.84      0.82      1519
weighted avg       0.85      0.82      0.82      1519

0.8229098090849243


In [50]:
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))
print(accuracy_score(y_test,y_pred1))

[[824  62]
 [117 516]]
              precision    recall  f1-score   support

           0       0.88      0.93      0.90       886
           1       0.89      0.82      0.85       633

    accuracy                           0.88      1519
   macro avg       0.88      0.87      0.88      1519
weighted avg       0.88      0.88      0.88      1519

0.8821593153390388


In [51]:
print(confusion_matrix(y_test,y_pred3))
print(classification_report(y_test,y_pred3))
print(accuracy_score(y_test,y_pred3))

[[754 132]
 [194 439]]
              precision    recall  f1-score   support

           0       0.80      0.85      0.82       886
           1       0.77      0.69      0.73       633

    accuracy                           0.79      1519
   macro avg       0.78      0.77      0.78      1519
weighted avg       0.78      0.79      0.78      1519

0.7853851217906518


### Discussion

1) bernoulli accuracy is the highest 
2) precision is highest in guassain distribution 
3) f1 score is highest of multinomial 
4) bernoulli accuracy is high because our most feature have value between 0 and 1 also there are no strong dependencies between features. which makes the model accuracy very high as compared to the other.


### Conclusion 
1) here false positve play crucial role in detecting spam mail. so it preferred to use  multinomial becuase its precision value is balanced to both classes as well as high.
2) there can be missing value in the dataset do eda properly 
 