# PART 1

### ANS 1

data structurea are used to represent  and manipulate data.
1) Variables: it is used to hold vales which can be modified.
2) Sparse Tensors: it is used to represent data mainly of zeros.
3) Ragged Tensors: ragged tensores are used to rperesent of matrix of different sizes.
4) Tensores: used to represent multi-dimensional array.

### ANS 2

difference between constant and variable:
1) constant value cannot be changed but variables values can be changed.
2) constant are immutable tensors and variables are mutuable tensors.

### ANS 3

In [2]:
import tensorflow as tf

In [5]:
matrix_1=tf.constant([[1,2,3],[2,5,6]])
matrix_2=tf.constant([[9,8,7],[5,6,7]])

In [6]:
matrix_add=matrix_1+matrix_2

In [7]:
matrix_add

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 10, 10],
       [ 7, 11, 13]])>

In [8]:
matrix_mult=matrix_1*matrix_2

In [9]:
matrix_mult

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 9, 16, 21],
       [10, 30, 42]])>

In [10]:
ele=matrix_1*4

In [11]:
ele

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4,  8, 12],
       [ 8, 20, 24]])>

In [12]:
matrix_subtract=matrix_1-matrix_2

In [13]:
matrix_subtract

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-8, -6, -4],
       [-3, -1, -1]])>

# PART 2

## TASK 1

### ANS 1

In [18]:
matrix_a=tf.random.normal(shape=(3,3))

In [19]:
matrix_a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7446679 ,  0.13884327,  1.522476  ],
       [-1.9798311 ,  0.99315596,  1.334364  ],
       [-0.59111017, -1.0620196 ,  0.01999022]], dtype=float32)>

### ANS 2

In [29]:
matrix_b=tf.random.truncated_normal(shape=(4,4))

In [30]:
matrix_b

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.04745372, -1.2027674 , -0.3682536 , -1.2471641 ],
       [ 0.19134709,  0.31112495, -0.0991949 , -0.18521705],
       [ 1.3924824 ,  0.26447025,  0.27631745,  0.82112664],
       [ 0.36811656, -0.8850986 , -1.4402989 ,  0.6779054 ]],
      dtype=float32)>

### ANS 3

In [31]:
matrix_c=tf.random.normal(shape=(2,2),mean=3,stddev=0.5)

In [32]:
matrix_c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.3731413, 3.419585 ],
       [2.8533232, 2.7349706]], dtype=float32)>

### ANS 4

In [41]:
reshaped_matrix_a=tf.pad(matrix_a,paddings=[[0,1],[0,1]])

In [39]:
reshaped_matrix_a

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.7446679 ,  0.13884327,  1.522476  ,  0.        ],
       [-1.9798311 ,  0.99315596,  1.334364  ,  0.        ],
       [-0.59111017, -1.0620196 ,  0.01999022,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]],
      dtype=float32)>

In [42]:
matrix_d=reshaped_matrix_a-matrix_b

In [44]:
matrix_d

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.6972142 ,  1.3416107 ,  1.8907295 ,  1.2471641 ],
       [-2.171178  ,  0.68203104,  1.433559  ,  0.18521705],
       [-1.9835925 , -1.3264898 , -0.2563272 , -0.82112664],
       [-0.36811656,  0.8850986 ,  1.4402989 , -0.6779054 ]],
      dtype=float32)>

### ANS 5

In [45]:
matrix_e=reshaped_matrix_a*matrix_d

## TASK 2

### ANS 1

In [62]:
matrix_f=tf.random.uniform(shape=(3,3))

In [63]:
matrix_f

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.7702664 , 0.04103351, 0.649106  ],
       [0.6826271 , 0.45881116, 0.45402122],
       [0.4998113 , 0.27239215, 0.81784415]], dtype=float32)>

## ANS 2

In [64]:
matrix_g=tf.transpose(matrix_f)

In [65]:
matrix_g

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.7702664 , 0.6826271 , 0.4998113 ],
       [0.04103351, 0.45881116, 0.27239215],
       [0.649106  , 0.45402122, 0.81784415]], dtype=float32)>

## ANS 3

In [61]:
matrix_h=tf.exp(matrix_f)

In [66]:
matrix_h

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.0386314, 1.0841067, 1.9642775],
       [1.3902043, 1.2754403, 2.4276834],
       [2.5686803, 1.4969524, 1.2695886]], dtype=float32)>

## ANS 4

In [75]:
matrix_l=tf.concat([matrix_f,matrix_g],axis=1)

In [76]:
matrix_1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 5, 6]])>

## ANS 5

In [77]:
matrix_j=tf.concat([matrix_f,matrix_g],axis=0)

In [78]:
matrix_j

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[0.7702664 , 0.04103351, 0.649106  ],
       [0.6826271 , 0.45881116, 0.45402122],
       [0.4998113 , 0.27239215, 0.81784415],
       [0.7702664 , 0.6826271 , 0.4998113 ],
       [0.04103351, 0.45881116, 0.27239215],
       [0.649106  , 0.45402122, 0.81784415]], dtype=float32)>